Repository Opensource-Java-Project/FE, pull requests merged in 2023-11, with the labels that each got.

#5 feature : Login Page, Zustand
  package-lock.json
  package.json
  src/App.css
  src/api/authApi.js
  src/index.css
  src/pages/Login.jsx
  src/pages/Register.jsx
  src/store/userStore.js
Labels: feature

#8 first time commit
  src/pages/Main.jsx
Labels: feature

#10 merge test, feature
  src/App.js
  src/apis/IdPwApi.js
  src/apis/authApi.js
  src/apis/getDataApi.js
  src/apis/instance.js
  src/components/common/TopBanner/TopBanner.jsx
  src/components/common/TopBanner/section/LoginAndOut.jsx
  src/components/common/TopBanner/section/LogoImg.jsx
  src/hooks/useAuth.js
  src/hooks/useGetPost.js
  src/hooks/useGetUserData.js
  src/hooks/useLoggedIn.js
  src/hooks/useLoggedInRedirect.js
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Post.jsx
  src/pages/Register.jsx
  src/store/useLoggedInStore.js
  src/store/useUserDataStore.js
Labels: feature, refactor

#11 Post Page와 예약 시스템 추가
  package-lock.json
  package.json
  src/App.js
  src/apis/IdPwApi.js
  src/apis/getDataApi.js
  src/apis/postDataApi.js
  src/components/Reservation/Reservation.jsx
  src/components/common/TopBanner/TopBanner.jsx
  src/components/common/TopBanner/index.js
  src/components/common/TopBanner/section/LogoImg.jsx
  src/hooks/useGetPost.js
  src/hooks/useLoggedInRedirect.js
  src/pages/Login.jsx
  src/pages/Post.jsx
  src/pages/Register.jsx
Labels: feature

#12 css추가 및 로직 수정
  package-lock.json
  package.json
  public/asset/img/logo.png
  public/asset/img/testPostImg.png
  src/App.js
  src/apis/getDataApi.js
  src/apis/postDataApi.js
  src/components/Reservation/Reservation.jsx
  src/components/common/TopBanner/TopBanner.jsx
  src/components/common/TopBanner/section/LoginAndOut.jsx
  src/components/common/TopBanner/section/LogoImg.jsx
  src/components/common/TopBanner/section/ProfileImg.jsx
  src/hooks/useAuth.js
  src/hooks/useGetUserData.js
  src/hooks/useLoggedInRedirect.js
  src/pages/Login.jsx
  src/pages/Post.jsx
  src/pages/Register.jsx
  src/store/useLoggedInStore.js
Labels: fix, feature

#13 feature : 세부기능 및 CSS
  public/asset/img/profileImage.png
  public/index.html
  src/App.js
  src/apis/getDataApi.js
  src/apis/postDataApi.js
  src/components/Reservation/Reservation.jsx
  src/components/common/Footer.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/index.js
  src/components/common/Header/section/LoginAndOut.jsx
  src/components/common/Header/section/LogoImg.jsx
  src/components/common/Header/section/ProfileImg.jsx
  src/components/common/Layout.jsx
  src/components/common/TopBanner/index.js
  src/components/common/TopBanner/section/ProfileImg.jsx
  src/hooks/useAuth.js
  src/pages/Post.jsx
  src/store/useUserStore.js
  src/utils/createRange.js
Labels: feature, refactor

#14 오류 수정 및 Uload 기능 대략 구현
  src/App.js
  src/apis/instance.js
  src/apis/postDataApi.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/section/ProfileImg.jsx
  src/components/common/Header/section/UploadButton.jsx
  src/hooks/useAuth.js
  src/pages/Main.jsx
  src/pages/Post.jsx
  src/pages/Upload.jsx
  src/store/useMessageStore.jsx
Labels: fix, feature, refactor

#18 feature/UploadButton
  src/components/common/Header/section/UploadButton.jsx
  src/store/useMessageStore.js
Labels: feature

#19 Feature/main
  .github/ISSUE_TEMPLATE/-feature--.md
  src/apis/instance.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/section/UploadButton.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Register.jsx
  src/pages/Upload.jsx
Labels: refactor

#21 [Feature] 메인페이지 개발
  src/components/PostComponent/PostComponent.jsx
  src/components/PostComponent/index.js
  src/components/common/Header/section/UploadButton.jsx
  src/pages/Main.jsx
  src/pages/Post.jsx
Labels: feature
